# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "debian-12.4-aarch64/20231220"
  config.vm.hostname = "deb12pkg"
  config.vm.box_check_update = false
  config.vm.provision "shell", path: "provision.sh"
  config.vm.provider "parallels" do |vb, override|
    override.vm.network "forwarded_port", guest: 80,   host: 9998
  end
end



